name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize] #Without the 3 rows the events wont trigger on pull requests
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Install dependencies 
        run: npm install  
      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      - name: run test
        run: npm run test
      - name: e2e-tests
        run: npm run testPW
      - run: flyctl deploy --remote-only
        if: ${{ github.event_name == 'push' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        

