name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize] #Without the 3 rows the events wont trigger on pull requests

permissions: read-all

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: rjstone/discord-webhook-notify@v2

        with:
          node-version: '20'
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Install dependencies 
        run: npm install  
      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      - name: run test
        run: npm run test
      - name: e2e-tests
        run: npm run testPW
      - run: flyctl deploy --remote-only
        if: ${{ github.event_name == 'push' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      
      
      - name: succesfully building
        if: success()
        uses: rjstone/discord-webhook-notify@v2

        with: 
          webhookUrl: ${{ secrets.disco_url }}
          username: KirillosTY
          avatarUrl: https://igormiranda.com.br/wp-content/uploads/2021/08/Rick-Astley-Rickroll-Never-Gonna-Give-You-Up.jpg
          severity: info 
          color: '#ff00aa'
          title: PR test
          description: |
           **Repository**: [${{ github.repository }}](https://github.com/${{ github.repository }})
            **Workflow**: ${{ github.workflow }}
            **Run Number**: ${{ github.run_number }}
            **Run ID**: [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            **Event**: ${{ github.event_name }}
            **Actor**: ${{ github.actor }}
            **Ref**: ${{ github.ref }}
            **Commit**: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            **Job**: ${{ github.job }}
      - name: build failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v2

        with: 
          webhookUrl: ${{ secrets.disco_url }}
          username: KirillosTY
          avatarUrl: https://igormiranda.com.br/wp-content/uploads/2021/08/Rick-Astley-Rickroll-Never-Gonna-Give-You-Up.jpg
          severity: info 
          color: '#ff00aa'
          title: PR test
          description: |
            **Repository**: [${{ github.repository }}](https://github.com/${{ github.repository }})
            **Workflow**: ${{ github.workflow }}
            **Run Number**: ${{ github.run_number }}
            **Run ID**: [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            **Event**: ${{ github.event_name }}
            **Actor**: ${{ github.actor }}
            **Ref**: ${{ github.ref }}
            **Commit**: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            **Job**: ${{ github.job }}




  tag_release:  
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  discord_webhook_success:
    needs: [tag_release]
    runs-on: ubuntu-22.04
    steps:
      - uses: rjstone/discord-webhook-notify@v2
        if: success()
        with: 
          webhookUrl: ${{ secrets.disco_url }}
          username: KirillosTY
          avatarUrl: https://igormiranda.com.br/wp-content/uploads/2021/08/Rick-Astley-Rickroll-Never-Gonna-Give-You-Up.jpg
          severity: info 
          color: '#ff00aa'
          title: PR test
          description: |
            **Repository**: [${{ github.repository }}](https://github.com/KirillosTY/full-stack-open-pokedex/${{ github.repository }})
            **Workflow**: ${{ github.workflow }}
            **Event**: ${{ github.event_name }}
            **Triggering Actor**: ${{ github.actor }}
            **Jobs**: ${{github.job}}
            **severity**: warn

          
  discord_webhook_failure:
    needs: [simple_deployment_pipeline,tag_release]
    runs-on: ubuntu-22.04
    steps:
      - uses: rjstone/discord-webhook-notify@v2
        if: ${{failure()}}
        with: 
          webhookUrl: ${{ secrets.disco_url }}
          username: KirillosTY
          avatarUrl: https://igormiranda.com.br/wp-content/uploads/2021/08/Rick-Astley-Rickroll-Never-Gonna-Give-You-Up.jpg
          severity: info 
          color: '#ff00aa'
          title: PR test
          description: |
            **Repository**: [${{ github.repository }}](https://github.com/KirillosTY/full-stack-open-pokedex/${{ github.repository }})
            **Workflow**: ${{ github.workflow }}
            **Event**: ${{ github.event_name }}
            **Triggering Actor**: ${{ github.actor }}
            **Jobs**: ${{github.job}}
            **severity**: warn
